### ISSUE TITLE
atom-shell-9999 hangs on bootstrap

### ISSUE THREAD

**Issue by ExecutorElassus** [emcek/gentoo.mipl#9]
emerging atom-shell-9999 stops at this point:

```
git checkout --quiet f7574aa6cc2c819430c1f05e9a1a1a666ef8169b
GIT update -->
   repository:               https://github.com/boto/boto.git
   at the commit:            f7574aa6cc2c819430c1f05e9a1a1a666ef8169b
>>> Source unpacked in /var/tmp/portage/dev-util/atom-shell-9999/work
>>> Preparing source in /var/tmp/portage/dev-util/atom-shell-9999/work/atom-shell-9999 ...
 * Bootstrap atom-shell source
```

strace on the process shows `epoll_wait(4,` with no further information. 

How can I nail down what part of bootstrapping is hanging?

Cheers,

EE

**Comment by emcek** [comment]
@ExecutorElassus atom-shell doesn't really exist anymore, since it was rename to [electron](https://github.com/atom/electron)
So this live ebuild was working around when last [atom-shell-0.23.0](https://github.com/atom/electron/releases/tag/v0.23.0) version. But now [electron-0.34.1](https://github.com/atom/electron/releases/tag/v0.34.1) is completely different subject.

I belied you want emerge atom editor, so please use current binary version [1.0.19](https://github.com/emcek/gentoo.mipl/blob/master/app-editors/atom-bin/atom-bin-1.0.19.ebuild) or if you don't want bin version use older one [1.0.11](https://github.com/emcek/gentoo.mipl/blob/master/app-editors/atom/atom-1.0.11-r1.ebuild)

This ebuild is TBD.
